add_newline = false

[character]
error_symbol 		= "[λ](bold red) "
format 			= "$symbol"
success_symbol  	= "[λ](bold green) "

[directory]
disabled 		= false
format 		  	= "[$path]($style) "
style 		  	= "bold cyan"
truncate_to_repo  	= true
truncation_length 	= 1

[hostname]
ssh_only 		= false
style    		= "bright-green bold"
format   		= "| [$hostname]($style) "

[username]
style_user 		= "purple bold"
style_root 		= "red bold"
disabled   		= false
show_always		= true
format			= "[$user]($style) "

[battery]
disabled        = true
