# remove newline at start of the prompt
add_newline = false

# format character
[character]
success_symbol      = "[Î»](bold #00ff00)"
error_symbol        = "[Î»](bold #ff0000)"

format              = "$symbol "

# format username
[username]
style_root          = "bold #ff8b2b"
style_user          = "bold #2ca5ff"
show_always         = true

format              = "[$user]($style) | "

# format directory
[directory]
truncation_length   = 1
truncate_to_repo    = true
read_only           = "ðŸ”’"
read_only_style     = "#ffff00"
style               = "#46c16d"

format              = "\\[[$path]($style)[$readonly]($read_only_style)\\] "

# format hostname
[hostname]
ssh_only            = false
style               = "bold #ff5be8"

format              = "[$hostname]($style) "
